local config = require("testpilot.config")

describe("testpilot.config", function()
  before_each(function()
    config.reset()
  end)

  describe("defaults", function()
    it("has open_method = vsplit", function()
      assert.are.equal("vsplit", config.get().open_method)
    end)

    it("has notify = true", function()
      assert.is_true(config.get().notify)
    end)
  end)

  describe("apply", function()
    it("merges user options with defaults", function()
      config.apply({ open_method = "split" })
      assert.are.equal("split", config.get().open_method)
      assert.is_true(config.get().notify)
    end)

    it("handles empty opts", function()
      config.apply({})
      assert.are.equal("vsplit", config.get().open_method)
    end)

    it("handles nil opts", function()
      config.apply(nil)
      assert.are.equal("vsplit", config.get().open_method)
    end)
  end)

  describe("reset", function()
    it("restores defaults after apply", function()
      config.apply({ open_method = "edit", notify = false })
      config.reset()
      assert.are.equal("vsplit", config.get().open_method)
      assert.is_true(config.get().notify)
    end)
  end)
end)
