local go = require("testpilot.languages.go")
local resolver = require("testpilot.resolver")

describe("testpilot.languages.go", function()
  describe("candidates", function()
    it("returns _test.go candidate for a .go file", function()
      local result = go.candidates("/project/pkg/", "handler.go")
      assert.are.same({ "/project/pkg/handler_test.go" }, result)
    end)

    it("returns empty for non-.go file", function()
      local result = go.candidates("/project/", "main.py")
      assert.are.same({}, result)
    end)

    it("handles files already named _test.go", function()
      local result = go.candidates("/project/", "handler_test.go")
      assert.are.same({ "/project/handler_test_test.go" }, result)
    end)

    it("handles path with trailing slash", function()
      local result = go.candidates("/a/b/c/", "server.go")
      assert.are.same({ "/a/b/c/server_test.go" }, result)
    end)
  end)
end)

describe("testpilot.resolver", function()
  describe("resolve", function()
    it("dispatches .go files to the Go resolver", function()
      local candidates, err = resolver.resolve("/project/pkg/handler.go")
      assert.is_nil(err)
      assert.are.same({ "/project/pkg/handler_test.go" }, candidates)
    end)

    it("returns error for unsupported extension", function()
      local candidates, err = resolver.resolve("/project/main.rb")
      assert.is_nil(candidates)
      assert.is_truthy(err:find("No resolver for extension"))
    end)

    it("returns error for file with no extension", function()
      local candidates, err = resolver.resolve("/project/Makefile")
      assert.is_nil(candidates)
      assert.is_truthy(err:find("No resolver for extension"))
    end)
  end)
end)
